apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zrqlka8ir-go 
  janus-idp.io/tekton: zrqlka8ir-go
  backstage.io/kubernetes-id: zrqlka8ir-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zrqlka8ir-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  